#!/bin/bash
# Ubuntu + awscli Docker image
# Type: Shell Access Based (Opens bash shell)
# Use: Generally used to run from scripts or automation tools
# Author: Satish Gaikwad <satish@satishweb.com>

# We will always take latest stable ubuntu docker image as base image
FROM satishweb/awscli
MAINTAINER Satish Gaikwad <satish@satishweb.com>

# We are just removing entrypoint and running default command to open shell for scripted/automated use of awscli
CMD ["/bin/bash"]
